# Site settings
name: Auuu Nya Blog
email: mu1er@qq.com
author: Auuu Nya
url: http://mu1er.com
resume_site: https://github.com/mu1er
github: https://github.com/mu1er/
# baseurl: "/mu1er"
description: I Like It!
meta_description: Auuu Nya,Go,Python,HTML,Css,javascript
motto: Auuu Nya Blog.
banner: 选择自己所喜欢的,喜欢自己所选择的。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: Mu1er

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

